{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}-main
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  index.ts: |
    // Minimal entrypoint for edge runtime
    Deno.serve((_req) => new Response(JSON.stringify({ ok: true } ), {
      headers: { "content-type": "application/json" }
    }));
{{- end }}
